const D = require("./dev-core");

console.log(D);


const RS = D.RS;            // all available REGISTERS

const M00 = D.M00;
const M01 = D.M01;
const M02 = D.M02;
const M03 = D.M03; 
const M04 = D.M04;
const M05 = D.M05; 
const M06 = D.M06;
const M07 = D.M07;
const M08 = D.M08;
const M09 = D.M09;
const M10 = D.M10;
const M11 = D.M11;
const M12 = D.M12;
const M13 = D.M13; 
const M14 = D.M14;
const M15 = D.M15;


// M00(1,                                      'SET R0 TO 1');             RS["00"] === 1 || D.THROWE();

// M01(2,                                      'SET R1 TO 2');             RS["01"] === 2 || D.THROWE();
// M02(3,                                      'SET R2 TO 3');             RS["02"] === 3 || D.THROWE();

// D.AND(RS["02"],     RS["01"],   RS["00"],   '0 = 2 & 1');               RS["02"] === 0 || D.THROWE();
// D.XOR(RS["02"],     RS["01",    RS["00"],   '3 = 2 ^ 1']);              RS["02"] === 3 || D.THROWE();

console.log("ensure to test the assembly code");

let z = 0;
function aeb(){return "a"!=="b"};
function aebs(){return z++,"success"};

D.IF0(aeb,    aebs) === "success" || D.THROWE();
D.IF1(aeb,    aebs, aebs) === "success" && z === 2 || D.THROWE();
D.IF2(aeb,    aebs, aebs, aeb, aebs) === "success" && z === 3 || D.THROWE();

// D.IFZ

D.SWITCH
.createFrom(new Error())
.case(e => e instanceof Error, e => console.error('timeout', e))
.case(e => e instanceof ErrorEvent, () => e => console.error('connection', e))
.else(e => log.error('Unknown error', e))
.execute()

D.TRY(function(){throw new Error()}) === undefined || D.THROWE();

D.TRYCATCH(function(){throw new Error()},function(e){return e});
D.TRYCATCHFINALLY(
    function(){throw new Error()},
    function(e){console.error(e)},
    function(){return }
);

D.ISBOOLEAN(function(){})   === false || D.THROWE();
D.ISNOTBOOLEAN(function(){})=== true  || D.THROWE();

D.ISNUMBER(1) === true || D.THROWE()
D.ISNOTNUMBER("2") === true || D.THROWE()
D.ISSTRING("") === true || D.THROWE()
D.ISNOTSTRING(function(){}) === true || D.THROWE()
D.ISJSON({}) === true || D.THROWE()
D.ISNOTJSON({}) === false || D.THROWE()
D.ISOBJECT({}) === true || D.THROWE()
D.ISNOTOBJECT({}) === false || D.THROWE()
D.ISARRAY([]) === true || D.THROWE()
D.ISNOTARRAY([]) === false || D.THROWE()
D.ISSYMBOL([]) === false || D.THROWE()
D.ISNOTSYMBOL({}) === true || D.THROWE()
D.ISFUNCTION(function(){}) === true || D.THROWE()
D.ISNOTFUNCTION(()=>{}) === false || D.THROWE()
D.ISTHIS(function(){}) === true || D.THROWE()
D.ISNOTTHIS(()=>{}) === true || D.THROWE()
D.ISLAMBDA(()=>{}) === true || D.THROWE()
D.ISNOTLAMBDA(()=>{}) === false || D.THROWE()
// D.ISANONYMOUS(function(){}) === true || D.THROWE()
// D.ISNOTANONYMOUS(()=>{}) === false || D.THROWE()
D.ISFUNC(function(){}) === true || D.THROWE()
D.ISNOTFUNC(()=>{}) === true || D.THROWE()
D.ISCLASS(class X {}) === true || D.THROWE()
D.ISNOTCLASS(()=>{}) === true || D.THROWE()
D.ISNEWABLE(function(){}) === true || D.THROWE()
D.ISUNDEFINED(undefined) === true || D.THROWE()
D.ISNOTUNDEFINED(false) === true || D.THROWE()
D.ISNULL(null) === true || D.THROWE()
D.ISNOTNULL(undefined) === true || D.THROWE()
D.ISSAFE(1) === true || D.THROWE()
D.ISNOTSAFE(1 << 31 + 1 << 4) === true || D.THROWE()
D.ISTRUE(true) === true || D.THROWE()
D.ISNOTTRUE(true) === false || D.THROWE()
// D.ISFALSE() === || D.THROWE()
// D.ISNOTFALSE() === || D.THROWE()
// D.ISINFINITY() === || D.THROWE()
// D.ISNOTINFINITY() === || D.THROWE()
// D.ISFINITE() === || D.THROWE()
// D.ISNOTFINITE() === || D.THROWE()
// D.ISMAXVALUE() === || D.THROWE()
// D.ISNOTMAXVALUE() === || D.THROWE()
// D.ISMINVALUE() === || D.THROWE()
// D.ISNOTMINVALUE() === || D.THROWE()
// D.ISMAXSAFEVALUE() === || D.THROWE()
// D.ISNOTMAXSAFEVALUE() === || D.THROWE()
// D.ISMINSAFEVALUE() === || D.THROWE()
// D.ISNOTMINSAFEVALUE() === || D.THROWE()
// D.ISNAN() === || D.THROWE()
// D.ISNOTNAN() === || D.THROWE()
// D.ISPOSITIVE() === || D.THROWE()
// D.ISNOTPOSITIVE() === || D.THROWE()
// D.ISNEGATIVE() === || D.THROWE()
// D.ISNOTNEGATIVE() === || D.THROWE()
// D.ISZERO() === || D.THROWE()
// D.ISNOTZERO() === || D.THROWE()
// D.ISFLOAT() === || D.THROWE()
// D.ISNOTFLOAT() === || D.THROWE()
// D.ISINTEGER() === || D.THROWE()
// D.ISNOTINTEGER() === || D.THROWE()
// D.ISALPHA() === || D.THROWE()
// D.ISNOTALPHA() === || D.THROWE()
// D.ISLOWERCASE() === || D.THROWE()
// D.ISNOTLOWERCASE() === || D.THROWE()
// D.ISUPPERCASE() === || D.THROWE()
// D.ISNOTUPPERCASE() === || D.THROWE()
// D.ISEMPTY() === || D.THROWE()
// D.ISNOTEMPTY() === || D.THROWE()
// D.GETNAME() === || D.THROWE()
// D.GETPARAMS() === || D.THROWE()
// D.GETALLPARAMS() === || D.THROWE()
// D.GETCOMMENTS() === || D.THROWE()
// D.GETALLCOMMENTS() === || D.THROWE()
// D.GETINPUTTYPE() === || D.THROWE()
// D.GETOUTPUTTYPE() === || D.THROWE()
// D.GETEXETYPE() === || D.THROWE()
// D.GETSTATEMENTS() === || D.THROWE()
// D.GETINNERMEM() === || D.THROWE()
// D.ASSERTINDEPENDENCE() === || D.THROWE()
// D.ASSERTCOMPOUND() === || D.THROWE()
// D.assertComplex() === || D.THROWE()
// D.NOTEMPTY() === || D.THROWE()
// D.HASPROPERTY() === || D.THROWE()
// D.ISDIVISIBLE() === || D.THROWE()
// D.ISEVEN() === || D.THROWE()
// D.ISEVENINTEGER() === || D.THROWE()
// D.ISEVENFLOAT() === || D.THROWE()
// D.ISODD() === || D.THROWE()
// D.ISODDINTEGER() === || D.THROWE()
// D.ISODDFLOAT() === || D.THROWE()
// D.PERIOD() === || D.THROWE()
// D.enforce_object_datas() === || D.THROWE()
// D.enforce_object_methods() === || D.THROWE()
// D.enforce_object_propsss() === || D.THROWE()
// D.enforce_object_nulls() === || D.THROWE()
// D.enforce_settings() === || D.THROWE()
// D.enforce_setting() === || D.THROWE()
// D.EVERY() === || D.THROWE()
// D.ALL() === || D.THROWE()
// D.NUMSTR() === || D.THROWE()
// D.NNUMSTR() === || D.THROWE()
// D.STRSTR() === || D.THROWE()
// D.NSTRSTR() === || D.THROWE()
// D.BOLARR() === || D.THROWE()
// D.NBOLARR() === || D.THROWE()
// D.NUMARR() === || D.THROWE()
// D.NNUMARR() === || D.THROWE()
// D.STRARR() === || D.THROWE()
// D.NSTRARR() === || D.THROWE()
// D.ARRARR() === || D.THROWE()
// D.NARRARR() === || D.THROWE()
// D.OBJARR() === || D.THROWE()
// D.NOBJARR() === || D.THROWE()
// D.JSNARR() === || D.THROWE()
// D.NJSNARR() === || D.THROWE()
// D.FNCARR() === || D.THROWE()
// D.NFNCARR() === || D.THROWE()
// D.OBJLMD() === || D.THROWE()
// D.NOBJLMD() === || D.THROWE()
// D.ANOARR() === || D.THROWE()
// D.NANOARR() === || D.THROWE()
// D.UNDARR() === || D.THROWE()
// D.NUNDARR() === || D.THROWE()
// D.NULARR() === || D.THROWE()
// D.NNULARR() === || D.THROWE()
// D.BOLJSN() === || D.THROWE()
// D.NBOLJSN() === || D.THROWE()
// D.NUMJSN() === || D.THROWE()
// D.NNUMJSN() === || D.THROWE()
// D.STRJSN() === || D.THROWE()
// D.NSTRJSN() === || D.THROWE()
// D.JSNJSN() === || D.THROWE()
// D.NJSNJSN() === || D.THROWE()
// D.OBJJSN() === || D.THROWE()
// D.NOBJJSN() === || D.THROWE()
// D.FNCJSN() === || D.THROWE()
// D.NFNCJSN() === || D.THROWE()
// D.ANOJSN() === || D.THROWE()
// D.NANOJSN() === || D.THROWE()
// D.UNDJSN() === || D.THROWE()
// D.NUNDJSN() === || D.THROWE()
// D.NULJSN() === || D.THROWE()
// D.NNULJSN() === || D.THROWE()
// D.__FINDHIGHESTARITY() === || D.THROWE()
// D.__APPLYSPECWITHARITY() === || D.THROWE()
// D.__FILTERUNDEFINED() === || D.THROWE()
// D.FLIPEXPORT() === || D.THROWE()
// D.ISINTEGER$1() === || D.THROWE()
// D.INDEXBYPATH() === || D.THROWE()
// D.BASESLICE() === || D.THROWE()
// D.MAPOBJECT() === || D.THROWE()
// D._CURRY3() === || D.THROWE()
// D.PARSEREGEX() === || D.THROWE()
// D.PARSEDATE() === || D.THROWE()
// D.PARSEERROR() === || D.THROWE()
// D._OBJECTIS() === || D.THROWE()
// D.DEFAULTTO() === || D.THROWE()
// D.Const() === || D.THROWE()
// D._CURRY1() === || D.THROWE()
// D._CURRY2() === || D.THROWE()
// D._ISPLACEHOLDER() === || D.THROWE()
// D._DISPATCHABLE() === || D.THROWE()
// D._ISOBJECT() === || D.THROWE()
// D._REDUCED() === || D.THROWE()
// D.XWRAP() === || D.THROWE()
// D._XWRAP() === || D.THROWE()
// D._REDUCE() === || D.THROWE()
// D._FILTER() === || D.THROWE()
// D._ISTRANSFORMER() === || D.THROWE()
// D._ISARRAY() === || D.THROWE()
// D._ISARRAYLIKE() === || D.THROWE()
// D._ARRAYREDUCE() === || D.THROWE()
// D._ARITY() === || D.THROWE()
// D.BIND() === || D.THROWE()
// D._METHODREDUCE() === || D.THROWE()
// D._ITERABLEREDUCE() === || D.THROWE()
// D._ISSTRING() === || D.THROWE()
// D._IDENTITY() === || D.THROWE()
// D.XFILTER() === || D.THROWE()
// D.ALWAYS() === || D.THROWE()
// D.APPLYSPEC() === || D.THROWE()
// D.COMPOSE() === || D.THROWE()
// D.CURRY() === || D.THROWE()
// D.F() === || D.THROWE()
// D.FLIP() === || D.THROWE()
// D.IDENTITY() === || D.THROWE()
// D.NEGATE() === || D.THROWE()
// D.PARTIAL() === || D.THROWE()
// D.PIPE() === || D.THROWE()
// D.T() === || D.THROWE()
// D.TAP() === || D.THROWE()
// D.DEC() === || D.THROWE()
// D.INC() === || D.THROWE()
// D.MATHMOD() === || D.THROWE()
// D.MEAN() === || D.THROWE()
// D.MEDIAN() === || D.THROWE()
// D.MODULO() === || D.THROWE()
// D.MULTIPLY() === || D.THROWE()
// D.SUM() === || D.THROWE()
// D.ANY() === || D.THROWE()
// D.APPEND() === || D.THROWE()
// D.CONCAT() === || D.THROWE()
// D.DIFFERENCE() === || D.THROWE()
// D.DROP() === || D.THROWE()
// D.DROPLAST() === || D.THROWE()
// D.ENDSWITH() === || D.THROWE()
// D.FILTER() === || D.THROWE()
// D.FIND() === || D.THROWE()
// D.FINDINDEX() === || D.THROWE()
// D.FLATTEN() === || D.THROWE()
// D.FOREACH() === || D.THROWE()
// D.FROMPAIRS() === || D.THROWE()
// D.GROUPBY() === || D.THROWE()
// D.GROUPWITH() === || D.THROWE()
// D.HEAD() === || D.THROWE()
// D.INCLUDES() === || D.THROWE()
// D.INDEXBY() === || D.THROWE()
// D.INDEXOF() === || D.THROWE()
// D.INIT() === || D.THROWE()
// D.INTERSECTION() === || D.THROWE()
// D.INTERSPERSE() === || D.THROWE()
// D.JOIN() === || D.THROWE()
// D.LAST() === || D.THROWE()
// D.LASTINDEXOF() === || D.THROWE()
// D.MAP() === || D.THROWE()
// D.NONE() === || D.THROWE()
// D.NTH() === || D.THROWE()
// D.PLUCK() === || D.THROWE()
// D.PREPEND() === || D.THROWE()
// D.RANGE() === || D.THROWE()
// D.REPEAT() === || D.THROWE()
// D.REVERSE() === || D.THROWE()
// D.SPLITEVERY() === || D.THROWE()
// D.STARTSWITH() === || D.THROWE()
// D.TAKE() === || D.THROWE()
// D.TAKELAST() === || D.THROWE()
// D.TIMES() === || D.THROWE()
// D.UNIQ() === || D.THROWE()
// D.UNIQWITH() === || D.THROWE()
// D._UPDATE() === || D.THROWE()
// D.WITHOUT() === || D.THROWE()
// D.ZIP() === || D.THROWE()
// D.ZIPOBJ() === || D.THROWE()
// D.DISSOC() === || D.THROWE()
// D.HAS() === || D.THROWE()
// D.LENS() === || D.THROWE()
// D.LENSINDEX() === || D.THROWE()
// D.LENSPATH() === || D.THROWE()
// D.ASSOC() === || D.THROWE()
// D.ASSOCPATH() === || D.THROWE()
// D.LENSPROP() === || D.THROWE()
// D.MERGE() === || D.THROWE()
// D.OMIT() === || D.THROWE()
// D.OVER() === || D.THROWE()
// D.PATH() === || D.THROWE()
// D.ALLPASS() === || D.THROWE()
// D.ANYPASS() === || D.THROWE()
// D.BOTH() === || D.THROWE()
// D.COMPLEMENT() === || D.THROWE()
// D.COND() === || D.THROWE()
// D.EITHER() === || D.THROWE()
// D.EQUALS() === || D.THROWE()
// D.IDENTICAL() === || D.THROWE()
// D.MAX() === || D.THROWE()
// D.MAXBy() === || D.THROWE()
// D.MIN() === || D.THROWE()
// D.MINBY() === || D.THROWE()
// D.ISNIL() === || D.THROWE()
// D.PICK() === || D.THROWE()
// D.PICKALL() === || D.THROWE()
// D.PROP() === || D.THROWE()
// D.PROPOR() === || D.THROWE()
// D.SET() === || D.THROWE()
// D.TOPAIRS() === || D.THROWE()
// D.VALUES() === || D.THROWE()
// D.VIEW() === || D.THROWE()
// D.THROWE() === || D.THROWE()
// D.THROWE0() === || D.THROWE()
// D.THROWE1() === || D.THROWE()
// D.THROWE2() === || D.THROWE()
// D.THROWEZ() === || D.THROWE()
// D.UNFINISHED() === || D.THROWE()
// D.UNFINSHED0() === || D.THROWE()
// D.UNFINSHED1() === || D.THROWE()
// D.UNFINSHEDZ() === || D.THROWE()
// D.BUG() === || D.THROWE()
// D.BUG0() === || D.THROWE()
// D.BUGZ() === || D.THROWE()
// D.MAINTENANCE() === || D.THROWE()
// D.MAINTENANCE0() === || D.THROWE()
// D.MAINTENANCEZ() === || D.THROWE()
// D.REVIEW() === || D.THROWE()
// D.REVIEW0() === || D.THROWE()
// D.REVIEWZ() === || D.THROWE()
// D.CLI() === || D.THROWE()
// D.REQUIRE() === || D.THROWE()
// D.UI() === || D.THROWE()
// D.CODE() === || D.THROWE()
// D.ANIMATE() === || D.THROWE()
// D.SAVE() === || D.THROWE()
// D.LOAD() === || D.THROWE()
// D.ENCRYPT() === || D.THROWE()
// D.RANDOM() === || D.THROWE()
// D.SHUFFLE() === || D.THROWE()
// D.COMPRESS() === || D.THROWE()
// D.GLOBAL() === || D.THROWE()
// D.VAR() === || D.THROWE()
// D.LET() === || D.THROWE()
// D.CONST() === || D.THROWE()
// D.RULE() === || D.THROWE()
// D.PROTOCOL() === || D.THROWE()
// D.NAMINGSYSTEM() === || D.THROWE()
// D.NUMBER() === || D.THROWE()
// D.BOOLEAN() === || D.THROWE()
// D.STRING() === || D.THROWE()
// D.ARRAY() === || D.THROWE()
// D.OBJECT() === || D.THROWE()
// D.SYMBOL() === || D.THROWE()
// D.FUNCTION() === || D.THROWE()
// D.LAMBDA() === || D.THROWE()
// D.CLASS() === || D.THROWE()
// D.NULL() === || D.THROWE()
// D.UNDEFINED() === || D.THROWE()
// D.FAKENATIVECODE() === || D.THROWE()
// D.CAPSULE() === || D.THROWE()
// D.VOBJ() === || D.THROWE()
// D.VNUM() === || D.THROWE()
// D.VSTR() === || D.THROWE()
// D.VFNC() === || D.THROWE()
// D.VLMD() === || D.THROWE()
// D.VSYM() === || D.THROWE()
// D.VSET() === || D.THROWE()
// D.VCLA() === || D.THROWE()
// D.VARR() === || D.THROWE()
// D.VUND() === || D.THROWE()
// D.VNUL() === || D.THROWE()
// D.VBOL() === || D.THROWE()
// D.DTYPE() === || D.THROWE()
// D.TYPETRUTHY() === || D.THROWE()
// D.TYPEFALSEY() === || D.THROWE()
// D.TYPESTATE() === || D.THROWE()
// D.PROPSALTERED() === || D.THROWE()
// D.IS() === || D.THROWE()
// D.TOBINARY() === || D.THROWE()
// D.TOHEX() === || D.THROWE()
// D.TODEC() === || D.THROWE()
// D.TOBASE() === || D.THROWE()
// D.TODATATYPE() === || D.THROWE()
// D.INTERFACESTRICT() === || D.THROWE()
// D.INTERFACELOOSE() === || D.THROWE()
// D.VALIDATE() === || D.THROWE()
// D.BLOCK() === || D.THROWE()
// D.SPEC() === || D.THROWE()
// D.DELETEPROPKEY() === || D.THROWE()
// D.DELETEPROPVALUE() === || D.THROWE()
// D.KEYS() === || D.THROWE()
// D.FUNC0BLOCK() === || D.THROWE()
// D.FUNC0VALIDATE() === || D.THROWE()
// D.INHERITCONFIG() === || D.THROWE()
// D.CONFIGMAIN() === || D.THROWE()
// D.PARSEFUNC() === || D.THROWE()
// D.parserClass() === || D.THROWE()
// D.DATA() === || D.THROWE()
// D.DATAPUBLIC() === || D.THROWE()
// D.DATAPRIVATE() === || D.THROWE()
// D.DATAPROTECT() === || D.THROWE()
// D.DATASTATIC() === || D.THROWE()
// D.DATAINTERNAL() === || D.THROWE()
// D.DATAGET() === || D.THROWE()
// D.DATASET() === || D.THROWE()
// D.METHOD() === || D.THROWE()
// D.METHODPUBLIC() === || D.THROWE()
// D.METHODPRIVATE() === || D.THROWE()
// D.METHODPROTECT() === || D.THROWE()
// D.METHODSTATIC() === || D.THROWE()
// D.METHODINTERNAL() === || D.THROWE()
// D.METHODGET() === || D.THROWE()
// D.METHODSET() === || D.THROWE()
// D.KINDA() === || D.THROWE()
// D.TO() === || D.THROWE()
// D.ESSENTIAL() === || D.THROWE()
// D.CHARS() === || D.THROWE()
// D.TRIM() === || D.THROWE()
// D.SWAP() === || D.THROWE()
// D.LIST() === || D.THROWE()
// D.POPULATION() === || D.THROWE()
// D.LOGIC() === || D.THROWE()
// D.VISUAL() === || D.THROWE()
// D.VOCAL() === || D.THROWE()
// D.SOUND() === || D.THROWE()
// D.INTERFACECLASSIFICATIONS() === || D.THROWE()
// D.CREATE() === || D.THROWE()
// D.READ() === || D.THROWE()
// D.UPDATE() === || D.THROWE()
// D.DELETE() === || D.THROWE()
// D.FINDDEADCODE() === || D.THROWE()
// D.PARAMS() === || D.THROWE()
// D.ATTRIBUTE() === || D.THROWE()
// D.SCHEMA() === || D.THROWE()
// D.MODEL() === || D.THROWE()
// D.CLOSURE() === || D.THROWE()
// D.REPLICATE() === || D.THROWE()
// D.CONFIG() === || D.THROWE()
// D.VALIDATION() === || D.THROWE()
// D.MEMASSIGN() === || D.THROWE()
// D.LOOP_FOR() === || D.THROWE()
// D.LOOP_FOREVER() === || D.THROWE()
// D.LOOP_WHILE() === || D.THROWE()
// D.LOOP_BREAK() === || D.THROWE()
// D.LOOP_CONTINUE() === || D.THROWE()
// D.LOOP_EACH() === || D.THROWE()
// D.LOOP_DEEP() === || D.THROWE()
// D.LOOP_DEEPRECURSION() === || D.THROWE()
// D.LOOP_CYCLE() === || D.THROWE()
// D.LOOP_FILTER() === || D.THROWE()
// D.LOOP_CHECKLIST() === || D.THROWE()
// D.LOOP_INTERVAL() === || D.THROWE()
// D.LOOP_WHEN() === || D.THROWE()
// D.LOOP_BEFORE() === || D.THROWE()
// D.LOOP_AFTER() === || D.THROWE()
// D.LOOP_NONEST() === || D.THROWE()
// D.LOOP_SPLIT() === || D.THROWE()
// D.LOOP_MERGE() === || D.THROWE()
// D.LOOP_SKIP() === || D.THROWE()
// D.LOOP_PINGPONG() === || D.THROWE()
// D.FUNC() === || D.THROWE()
// D.FUNCINTERFACE() === || D.THROWE()
// D.FUNCFAKEIFNULL() === || D.THROWE()
// D.FUNCINDEPEDENTVALIDATION() === || D.THROWE()
// D.FUNCCROSSEXAMINEVALIDATION() === || D.THROWE()
// D.FUNCMEMASSIGN() === || D.THROWE()
// D.FUNCTRETURN() === || D.THROWE()
// D.FUNCTEMPLATE() === || D.THROWE()
// D.FUNCCONFIGGLOBAL() === || D.THROWE()
// D.FUNCCONFIGINSTANCE() === || D.THROWE()
// D.FUNCCONFIGFUNC() === || D.THROWE()
// D.FUNCINCCONFIG() === || D.THROWE()
// D.FUNCCONFIG() === || D.THROWE()
// D.FUNCMETHS() === || D.THROWE()
// D.FUNCLOOPINTERFACE() === || D.THROWE()
// D.FUNCASSIGNINTERFACE() === || D.THROWE()
// D.intF() === || D.THROWE()
// D.intF_keys() === || D.THROWE()
// D.INPUT() === || D.THROWE()
// D.OUTPUT() === || D.THROWE()
// D.TEST() === || D.THROWE()
// D.AUDIT() === || D.THROWE()
// D.ASSERT() === || D.THROWE()
// D.SHOULD() === || D.THROWE()
// D.EXPECT() === || D.THROWE()
// D.LOG() === || D.THROWE()
// D.RESOLVE() === || D.THROWE()
// D.REJECT() === || D.THROWE()
// D.BEFORE() === || D.THROWE()
// D.AFTER() === || D.THROWE()
// D.BEFOREEACH() === || D.THROWE()
// D.AFTEREACH() === || D.THROWE()
// D.SPECDEV() === || D.THROWE()
// D.LAYERS() === || D.THROWE()
// D.CODEDECONSTRUCTOR() === || D.THROWE()
// D.DIFFERENTIALBUILDCODING() === || D.THROWE()
// D.INTUITLIST() === || D.THROWE()
// D.TREES() === || D.THROWE()
// D.WEB() === || D.THROWE()
// D.MATRIX() === || D.THROWE()
// D.STORE() === || D.THROWE()
// D.FETCH() === || D.THROWE()
// D.AMBIENT() === || D.THROWE()
// D.SORT() === || D.THROWE()
// D.QUANTIFY() === || D.THROWE()
// D.SEARCH() === || D.THROWE()
// D.MIDDLEWARE() === || D.THROWE()
// D.API() === || D.THROWE()
// D.SERVER() === || D.THROWE()
// D.CLIENT() === || D.THROWE()
// D.ZENDB() === || D.THROWE()
// D.PROXY() === || D.THROWE()
// D.CLUSTER() === || D.THROWE()
// D.DHCA() === || D.THROWE()
// D.SOCKET() === || D.THROWE()
// D.AUTOTEMPLATER() === || D.THROWE()
// D.SMARTCSS() === || D.THROWE()
// D.TAPJS() === || D.THROWE()
// D.COMPARTMENTALIZE() === || D.THROWE()
// D.PARADIGMS() === || D.THROWE()
// D.LEARNDEVCORE() === || D.THROWE()








